<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Guillermo Romero">
<meta name="dcterms.date" content="2023-03-13">

<title>EDS241: Assignment 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="romero_assignment2_files/libs/clipboard/clipboard.min.js"></script>
<script src="romero_assignment2_files/libs/quarto-html/quarto.js"></script>
<script src="romero_assignment2_files/libs/quarto-html/popper.min.js"></script>
<script src="romero_assignment2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="romero_assignment2_files/libs/quarto-html/anchor.min.js"></script>
<link href="romero_assignment2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="romero_assignment2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="romero_assignment2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="romero_assignment2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="romero_assignment2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">EDS241: Assignment 2</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Guillermo Romero </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 13, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="question-1" class="level2">
<h2 class="anchored" data-anchor-id="question-1">Question 1:</h2>
<p>Application of estimators based on the “treatment ignorability” assumption. The goal is to estimate the causal effect of maternal smoking during pregnancy on infant birth weight using the treatment ignorability assumptions (Lecture 6 &amp; 7).</p>
<p>The data are taken from the National Natality Detail Files, and the extract “SMOKING_EDS241.csv”’ is a random sample of all births in Pennsylvania during 1989-1991. Each observation is a mother-infant pair. The key variables are:</p>
<p>The outcome and treatment variables are:</p>
<ul>
<li><p>birthwgt = birth weight of infant in grams</p></li>
<li><p>tobacco = indicator for maternal smoking</p></li>
</ul>
<p>The control variables are: mage (mother’s age), meduc (mother’s education), mblack (=1 if mother black), alcohol (=1 if consumed alcohol during pregnancy), first (=1 if first child), diabete (=1 if mother diabetic), anemia (=1 if mother anemic)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
✔ ggplot2 3.4.0      ✔ purrr   1.0.1 
✔ tibble  3.1.8      ✔ dplyr   1.0.10
✔ tidyr   1.2.1      ✔ stringr 1.5.0 
✔ readr   2.1.3      ✔ forcats 0.5.2 
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Please cite as: 

 Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.
 R package version 5.2.3. https://CRAN.R-project.org/package=stargazer </code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(estimatr)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>corrplot 0.92 loaded</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ────────────────────────────────────── tidymodels 1.0.0 ──
✔ broom        1.0.2     ✔ rsample      1.1.1
✔ dials        1.1.0     ✔ tune         1.0.1
✔ infer        1.0.4     ✔ workflows    1.1.2
✔ modeldata    1.0.1     ✔ workflowsets 1.0.0
✔ parsnip      1.0.3     ✔ yardstick    1.1.0
✔ recipes      1.0.4     
── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
✖ scales::discard() masks purrr::discard()
✖ dplyr::filter()   masks stats::filter()
✖ recipes::fixed()  masks stringr::fixed()
✖ dplyr::lag()      masks stats::lag()
✖ yardstick::spec() masks readr::spec()
✖ recipes::step()   masks stats::step()
• Learn how to get started at https://www.tidymodels.org/start/</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>df_smoking <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"SMOKING_EDS241.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 94173 Columns: 9
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (9): anemia, diabete, tobacco, alcohol, mblack, first, mage, meduc, birt...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<p>What is the unadjusted mean difference in birth weight of infants with smoking and nonsmoking mothers?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>mean_weight_smk_nsmk <span class="ot">&lt;-</span> df_smoking <span class="sc">|&gt;</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(tobacco) <span class="sc">|&gt;</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_weight =</span> <span class="fu">mean</span>(birthwgt))</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(mean_weight_smk_nsmk<span class="sc">$</span>mean_weight[<span class="dv">1</span>] <span class="sc">-</span> mean_weight_smk_nsmk<span class="sc">$</span>mean_weight[<span class="dv">2</span>],<span class="dv">2</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 244.54</code></pre>
</div>
</div>
<p><strong>The unadjusted mean difference in birth weight of infants with smoking and nonsmoking mothers is 244.54.</strong></p>
<p><span class="smallcaps">Under what assumption does this correspond to the average treatment effect of maternal smoking during pregnancy on infant birth weight? Provide some simple empirical evidence for or against this assumption.</span></p>
<p><strong>This corresponds to the assumption of “treatment ignorability” conditional on pre treatment characteristics Xi (Rubin and Rosenbaum). There is evidence against this assumption as the distribution in the following boxplot is not balanced. Also, except for the control variable of the mother being diabetic, the F-statistic are large and the associated p-value is small, it suggests that the predictor variables in the model are jointly significant in explaining the variation in the outcome variable.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>bw <span class="ot">&lt;-</span> df_smoking <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tobacco =</span> <span class="fu">case_when</span>(tobacco <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"Non Smoker"</span>,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>                             tobacco <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"Smoker"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="fu">as.factor</span>(tobacco),</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> birthwgt,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> tobacco</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">+</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Tobacco"</span>,</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Birthweight"</span>) <span class="sc">+</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>meduc <span class="ot">&lt;-</span> df_smoking <span class="sc">|&gt;</span></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tobacco =</span> <span class="fu">case_when</span>(tobacco <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"Non Smoker"</span>,</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>                             tobacco <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"Smoker"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="fu">as.factor</span>(tobacco),</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> meduc,</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> tobacco</span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">+</span></span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Tobacco"</span>,</span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Mother's</span></span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a><span class="st">Education"</span>) <span class="sc">+</span></span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a>mage <span class="ot">&lt;-</span> df_smoking <span class="sc">|&gt;</span></span>
<span id="cb14-30"><a href="#cb14-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tobacco =</span> <span class="fu">case_when</span>(tobacco <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"Non Smoker"</span>,</span>
<span id="cb14-31"><a href="#cb14-31" aria-hidden="true" tabindex="-1"></a>                             tobacco <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"Smoker"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb14-32"><a href="#cb14-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(</span>
<span id="cb14-33"><a href="#cb14-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="fu">as.factor</span>(tobacco),</span>
<span id="cb14-34"><a href="#cb14-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> mage,</span>
<span id="cb14-35"><a href="#cb14-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> tobacco</span>
<span id="cb14-36"><a href="#cb14-36" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">+</span></span>
<span id="cb14-37"><a href="#cb14-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb14-38"><a href="#cb14-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Tobacco"</span>,</span>
<span id="cb14-39"><a href="#cb14-39" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Mother's</span></span>
<span id="cb14-40"><a href="#cb14-40" aria-hidden="true" tabindex="-1"></a><span class="st">Age"</span>) <span class="sc">+</span></span>
<span id="cb14-41"><a href="#cb14-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb14-42"><a href="#cb14-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-43"><a href="#cb14-43" aria-hidden="true" tabindex="-1"></a>patch <span class="ot">&lt;-</span> bw <span class="sc">/</span> meduc </span>
<span id="cb14-44"><a href="#cb14-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-45"><a href="#cb14-45" aria-hidden="true" tabindex="-1"></a>mage <span class="sc">+</span> patch</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="romero_assignment2_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># EXAMINE BALANCE IN COVARIATES</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># COVARIATE MEAN DIFFERENCES by tobacco</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> birthwgt <span class="sc">~</span> tobacco, <span class="at">data =</span> df_smoking)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> mblack <span class="sc">~</span> tobacco, <span class="at">data =</span> df_smoking)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> alcohol <span class="sc">~</span> tobacco, <span class="at">data =</span> df_smoking)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>m4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> first <span class="sc">~</span> tobacco, <span class="at">data =</span> df_smoking)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>m5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> diabete <span class="sc">~</span> tobacco, <span class="at">data =</span> df_smoking)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>m6 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> anemia <span class="sc">~</span> tobacco, <span class="at">data =</span> df_smoking)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>m7 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> mage <span class="sc">~</span> tobacco, <span class="at">data =</span> df_smoking)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>m8 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> meduc <span class="sc">~</span> tobacco , <span class="at">data =</span> df_smoking)</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>se_models <span class="ot">=</span> <span class="fu">starprep</span>(</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>  m1,</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>  m2,</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>  m3,</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>  m4,</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>  m5,</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>  m6,</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>  m7,</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>  m8,</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">stat =</span> <span class="fu">c</span>(<span class="st">"std.error"</span>),</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">se_type =</span> <span class="st">"HC2"</span>,</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">alpha =</span> <span class="fl">0.05</span></span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(m1, m2, m3, m4, m5, m6, m7, m8, <span class="at">se =</span> se_models, <span class="at">type =</span> <span class="st">"text"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
=============================================================================================================================
                                                                     Dependent variable:                                     
                                 --------------------------------------------------------------------------------------------
                                   birthwgt     mblack     alcohol      first    diabete   anemia       mage        meduc    
                                     (1)         (2)         (3)         (4)       (5)       (6)        (7)          (8)     
-----------------------------------------------------------------------------------------------------------------------------
tobacco                          -244.539***   0.027***    0.037***   -0.072***   0.0002  0.006***   -1.915***    -1.318***  
                                   (4.150)     (0.003)     (0.002)     (0.004)   (0.001)   (0.001)    (0.043)      (0.014)   
                                                                                                                             
Constant                         3,430.286***  0.109***    0.007***    0.436***  0.017*** 0.008***   27.453***    13.239***  
                                   (1.781)     (0.001)     (0.0003)    (0.002)   (0.0005) (0.0003)    (0.019)      (0.008)   
                                                                                                                             
-----------------------------------------------------------------------------------------------------------------------------
Observations                        94,173      94,173      94,173      94,173    94,173   94,173      94,173       94,173   
R2                                  0.037       0.001       0.015       0.003    0.00000    0.001      0.020        0.061    
Adjusted R2                         0.037       0.001       0.015       0.003    -0.00001   0.001      0.020        0.061    
Residual Std. Error (df = 94171)   493.753      0.317       0.118       0.493     0.131     0.094      5.290        2.048    
F Statistic (df = 1; 94171)      3,594.265*** 104.356*** 1,456.311*** 308.072***  0.021   65.196*** 1,919.595*** 6,072.205***
=============================================================================================================================
Note:                                                                                             *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
</section>
<section id="question-b" class="level2">
<h2 class="anchored" data-anchor-id="question-b">Question (b)</h2>
<p>Assume that maternal smoking is randomly assigned conditional on the observable covariates listed above. Estimate the effect of maternal smoking on birth weight using an OLS regression with linear controls for the covariates. Report the estimated coefficient on tobacco and its standard error.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> birthwgt <span class="sc">~</span> tobacco <span class="sc">+</span> <span class="fu">as.factor</span>(anemia) <span class="sc">+</span><span class="fu">as.factor</span>(diabete) <span class="sc">+</span> <span class="fu">as.factor</span>(alcohol) <span class="sc">+</span><span class="fu">as.factor</span>(mblack) <span class="sc">+</span><span class="fu">as.factor</span>(first) <span class="sc">+</span> mage <span class="sc">+</span> meduc <span class="sc">+</span> birthwgt, <span class="at">data=</span> df_smoking)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in model.matrix.default(mt, mf, contrasts): the response appeared on the
right-hand side and was dropped</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in model.matrix.default(mt, mf, contrasts): problem with term 9 in
model.matrix: no columns are assigned</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>se_models <span class="ot">=</span> <span class="fu">starprep</span>(mod , <span class="at">stat =</span> <span class="fu">c</span>(<span class="st">"std.error"</span>), <span class="at">se_type =</span> <span class="st">"HC1"</span>, <span class="at">alpha =</span> <span class="fl">0.05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in model.matrix.default(model): the response appeared on the right-hand
side and was dropped</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in model.matrix.default(model): problem with term 9 in model.matrix: no
columns are assigned</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(mod, <span class="at">se =</span> se_models, <span class="at">type=</span><span class="st">"text"</span>, <span class="at">omit =</span> <span class="st">"(LME)|(genus)|(species)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
===============================================
                        Dependent variable:    
                    ---------------------------
                             birthwgt          
-----------------------------------------------
tobacco                     -228.073***        
                              (4.277)          
                                               
as.factor(anemia)1            -4.796           
                             (17.864)          
                                               
as.factor(diabete)1          73.228***         
                             (13.232)          
                                               
as.factor(alcohol)1         -77.350***         
                             (14.034)          
                                               
as.factor(mblack)1          -240.030***        
                              (5.348)          
                                               
as.factor(first)1           -96.944***         
                              (3.488)          
                                               
mage                          -0.694*          
                              (0.368)          
                                               
meduc                        11.688***         
                              (0.862)          
                                               
Constant                   3,362.258***        
                             (12.076)          
                                               
-----------------------------------------------
Observations                  94,173           
R2                             0.072           
Adjusted R2                    0.072           
Residual Std. Error    484.733 (df = 94164)    
F Statistic         909.176*** (df = 8; 94164) 
===============================================
Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p><strong>The estimated coefficient on tobacco is -228.073 and the standar error is 4.277.</strong></p>
<ol start="3" type="a">
<li>Use the exact matching estimator to estimate the effect of maternal smoking on birth weight. For simplicity, consider the following covariates in your matching estimator: create a 0-1 indicator for mother’s age (= 1 if mage&gt; = 34), and a 0-1 indicator for mother’s education (1 if meduc&gt; = 16), mother’s race (mblack), and alcohol consumption indicator (alcohol). These 4 covariates will create 2 * 2 <em>*</em> 2 * 2 = 16 cells. Report the estimated average treatment effect of smoking on birthweight using the exact matching estimator and its linear regression analogue.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>df_matching <span class="ot">&lt;-</span> df_smoking <span class="sc">|&gt;</span> </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">mage_i =</span> <span class="fu">case_when</span>(mage <span class="sc">&gt;=</span> <span class="dv">34</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>                          <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">meduc_i =</span> <span class="fu">case_when</span>(meduc <span class="sc">&gt;=</span> <span class="dv">16</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>                           <span class="cn">TRUE</span> <span class="sc">~</span><span class="dv">0</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(birthwgt,tobacco, alcohol, mblack, mage_i, meduc_i)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>df_matching</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 94,173 × 6
   birthwgt tobacco alcohol mblack mage_i meduc_i
      &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
 1     4129       0       0      0      0       1
 2     3638       0       0      0      0       0
 3     3694       0       0      0      0       0
 4     3799       0       0      0      0       0
 5     3175       0       0      0      1       0
 6     2892       0       0      0      0       0
 7     3572       0       0      0      0       0
 8     3232       0       0      0      0       0
 9     3572       0       0      0      0       0
10     2820       0       0      1      1       0
# … with 94,163 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>linear_est <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> birthwgt <span class="sc">~</span> tobacco <span class="sc">+</span> alcohol <span class="sc">+</span> mblack <span class="sc">+</span> mage_i  <span class="sc">+</span> meduc_i, <span class="at">data =</span> df_matching)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>se_models <span class="ot">=</span> <span class="fu">starprep</span>(linear_est, <span class="at">stat =</span> <span class="fu">c</span>(<span class="st">"std.error"</span>), <span class="at">se_type =</span> <span class="st">"HC2"</span>, <span class="at">alpha =</span> <span class="fl">0.05</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(linear_est, <span class="at">se =</span> se_models, <span class="at">type=</span><span class="st">"text"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
================================================
                        Dependent variable:     
                    ----------------------------
                              birthwgt          
------------------------------------------------
tobacco                     -226.769***         
                              (4.213)           
                                                
alcohol                      -71.854***         
                              (14.073)          
                                                
mblack                      -238.643***         
                              (5.258)           
                                                
mage_i                         5.104            
                              (5.034)           
                                                
meduc_i                      42.064***          
                              (4.003)           
                                                
Constant                    3,445.583***        
                              (2.176)           
                                                
------------------------------------------------
Observations                   94,173           
R2                             0.062            
Adjusted R2                    0.062            
Residual Std. Error     487.182 (df = 94167)    
F Statistic         1,250.663*** (df = 5; 94167)
================================================
Note:                *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>TIA_table <span class="ot">&lt;-</span> df_smoking <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">mage_indicator =</span> <span class="fu">case_when</span>(mage <span class="sc">&gt;=</span> <span class="dv">34</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>                               mage <span class="sc">&lt;</span> <span class="dv">34</span> <span class="sc">~</span> <span class="dv">0</span>),</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">meduc_indicator =</span> <span class="fu">case_when</span>(meduc <span class="sc">&gt;=</span> <span class="dv">16</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>                                meduc <span class="sc">&lt;</span> <span class="dv">16</span> <span class="sc">~</span> <span class="dv">0</span>)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> <span class="co">#Create observed Y variable</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">factors =</span> <span class="fu">as.factor</span>(<span class="fu">paste0</span>(</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>    mblack, alcohol, mage_indicator, meduc_indicator</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>  ))) <span class="sc">%&gt;%</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(factors, tobacco) <span class="sc">%&gt;%</span></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n_obs =</span> <span class="fu">n</span>(),</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>            <span class="at">Y_mean =</span> <span class="fu">mean</span>(birthwgt, <span class="at">na.rm =</span> T)) <span class="sc">%&gt;%</span> <span class="co">#Calculate number of observations and Y mean by X by treatment cells</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gather</span>(variables, values, n_obs<span class="sc">:</span>Y_mean) <span class="sc">%&gt;%</span> <span class="co">#Reshape data</span></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">variables =</span> <span class="fu">paste0</span>(variables, <span class="st">"_"</span>, tobacco, <span class="at">sep =</span> <span class="st">""</span>)) <span class="sc">%&gt;%</span> <span class="co">#Combine the treatment and variables for reshaping</span></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">id_cols =</span> factors,</span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>              <span class="at">names_from =</span> variables,</span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>              <span class="at">values_from =</span> values) <span class="sc">%&gt;%</span> <span class="co">#Reshape data by treatment and X cell</span></span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span>  <span class="co">#Ungroup from X values</span></span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">Y_diff =</span> Y_mean_1 <span class="sc">-</span> Y_mean_0,</span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>    <span class="co">#calculate Y_diff</span></span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">w_ATE =</span> (n_obs_0 <span class="sc">+</span> n_obs_1) <span class="sc">/</span> (<span class="fu">sum</span>(n_obs_0) <span class="sc">+</span> <span class="fu">sum</span>(n_obs_1)),</span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">w_ATT =</span> n_obs_1 <span class="sc">/</span> <span class="fu">sum</span>(n_obs_1)</span>
<span id="cb29-25"><a href="#cb29-25" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> <span class="co">#calculate weights</span></span>
<span id="cb29-26"><a href="#cb29-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_if</span>(is.numeric, round, <span class="dv">2</span>) <span class="co">#Round data</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'factors'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(TIA_table,</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">type =</span> <span class="st">"text"</span>,</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">summary =</span> <span class="cn">FALSE</span>,</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
================================================================
   factors n_obs_0 n_obs_1 Y_mean_0 Y_mean_1 Y_diff  w_ATE w_ATT
----------------------------------------------------------------
1     1     44274   13443  3445.69  3220.25  -225.44 0.61  0.74 
2     2     13425    535   3483.02  3273.94  -209.08 0.15  0.03 
3     3     5115     976   3467.41  3171.42  -295.98 0.06  0.05 
4     4     4492     201   3487.19  3249.45  -237.74 0.05  0.01 
5     5      214     448   3450.28  3124.25  -326.03 0.01  0.02 
6     6      130     29    3510.95  3413.21  -97.74    0     0  
7     7      56      45    3358.32  3097.73  -260.59   0     0  
8     8      57      17    3534.91  3037.47  -497.44   0     0  
9     9     7007    1980   3195.97  3006.31  -189.66  0.1  0.11 
10   10      625     61    3319.22  3159.05  -160.17 0.01    0  
11   11      396     135   3185.08  2994.67  -190.41 0.01  0.01 
12   12      147     19    3328.29  2852.16  -476.13   0     0  
13   13      71      226   3120.07  2817.34  -302.73   0   0.01 
14   14       4      10     2983.5   3097.7   114.2    0     0  
15   15       7      26    2739.71  2846.38  106.67    0     0  
16   16       1       1      3459     2835    -624     0     0  
----------------------------------------------------------------</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>TIA_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 16 × 8
   factors n_obs_0 n_obs_1 Y_mean_0 Y_mean_1 Y_diff w_ATE w_ATT
   &lt;fct&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 0000      44274   13443    3446.    3220. -225.   0.61  0.74
 2 0001      13425     535    3483.    3274. -209.   0.15  0.03
 3 0010       5115     976    3467.    3171. -296.   0.06  0.05
 4 0011       4492     201    3487.    3249. -238.   0.05  0.01
 5 0100        214     448    3450.    3124. -326.   0.01  0.02
 6 0101        130      29    3511.    3413.  -97.7  0     0   
 7 0110         56      45    3358.    3098. -261.   0     0   
 8 0111         57      17    3535.    3037. -497.   0     0   
 9 1000       7007    1980    3196.    3006. -190.   0.1   0.11
10 1001        625      61    3319.    3159. -160.   0.01  0   
11 1010        396     135    3185.    2995. -190.   0.01  0.01
12 1011        147      19    3328.    2852. -476.   0     0   
13 1100         71     226    3120.    2817. -303.   0     0.01
14 1101          4      10    2984.    3098.  114.   0     0   
15 1110          7      26    2740.    2846.  107.   0     0   
16 1111          1       1    3459     2835  -624    0     0   </code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co">#MULTIVARIATE MATCHING ESTIMATES OF ATE AND ATT</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>ATE <span class="ot">=</span> <span class="fu">sum</span>((TIA_table<span class="sc">$</span>w_ATE) <span class="sc">*</span> (TIA_table<span class="sc">$</span>Y_diff))</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>ATE</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -224.2583</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>ATT <span class="ot">=</span> <span class="fu">sum</span>((TIA_table<span class="sc">$</span>w_ATT) <span class="sc">*</span> (TIA_table<span class="sc">$</span>Y_diff))</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>ATT</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -222.589</code></pre>
</div>
</div>
<p>ATE of exact matching estimator is -224.2583 and its linear regression analogue is -226.769.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>